module.exports = [
  {name: 'fitness'},
  {name: 'tennis'},
  {name: 'primary learning'},
  {name: 'robotics'},
  {name: 'strength of materials'},
  {name: 'health and safety'},
  {name: 'mechanics'},
  {name: 'skating'},
  {name: 'power electronics'},
  {name: 'social studies'},
  {name: 'physiotherapy'},
  {name: 'pharmacy'},
  {name: 'electronics'},
  {name: 'business'},
  {name: 'Japanese'},
  {name: 'forecasting'},
  {name: 'horse riding'},
  {name: 'computer graphics'},
  {name: 'history'},
  {name: 'philosophy'},
  {name: 'telecommunication'},
  {name: 'geology'},
  {name: 'chess'},
  {name: 'Spanish language'},
  {name: 'film production'},
  {name: 'German'},
  {name: 'psychology'},
  {name: 'logic'},
  {name: 'Italian language'},
  {name: 'logistics'},
  {name: 'biochemistry'},
  {name: 'career counseling'},
  {name: 'nature'},
  {name: 'journalism'},
  {name: 'ethics'},
  {name: 'architecture'},
  {name: 'political science'},
  {name: 'mathematical analysis'},
  {name: 'music'},
  {name: 'cultural'},
  {name: 'technical drawing'},
  {name: 'Latin'},
  {name: 'Turkish language'},
  {name: 'computer skills'},
  {name: 'skiing'},
  {name: 'biology'},
  {name: 'Chinese language'},
  {name: 'genetics'},
  {name: 'sculpture'},
  {name: 'ceramics'},
  {name: 'linguistics'},
  {name: 'painting and drawing'},
  {name: 'discrete mathematics'},
  {name: 'public relations'},
  {name: 'energetics'},
  {name: 'Ukrainian language'},
  {name: 'English'},
  {name: 'box'},
  {name: 'hospitality'},
  {name: 'administration'},
  {name: 'modeling'},
  {name: 'sign language'},
  {name: 'personal development'},
  {name: 'martial arts'},
  {name: 'snowboarding'},
  {name: 'memory techniques'},
  {name: 'Swedish'},
  {name: 'karate'},
  {name: 'econometrics'},
  {name: 'SEO'},
  {name: 'anatomy'},
  {name: 'public speeches'},
  {name: 'skateboarding'},
  {name: 'statistics'},
  {name: 'tourism'},
  {name: 'machine construction basics'},
  {name: 'speech therapy'},
  {name: 'accountancy'},
  {name: 'Korean language'},
  {name: 'motivation'},
  {name: 'informatics'},
  {name: 'histrionics'},
  {name: 'dance'},
  {name: 'sailing'},
  {name: 'microbiology'},
  {name: 'literature'},
  {name: 'history of art'},
  {name: 'geography'},
  {name: 'astronomy'},
  {name: 'physics'},
  {name: 'calligraphy'},
  {name: 'law'},
  {name: 'thermodynamics'},
  {name: 'agriculture'},
  {name: 'Russian'},
  {name: 'chemistry'},
  {name: 'self-defense'},
  {name: 'creating pages'},
  {name: 'algebra'},
  {name: 'automation'},
  {name: 'finance and accounting'},
  {name: 'maths'},
  {name: 'crocheting'},
  {name: 'sociology'},
  {name: 'education'},
  {name: 'medicine'},
  {name: 'Arabic'},
  {name: 'numerical methods'},
  {name: 'transport'},
  {name: 'electrotechnics'},
  {name: 'learning to sing'},
  {name: 'Norwegian language'},
  {name: 'marketing'},
  {name: 'ergonomics'},
  {name: 'entrepreneurship'},
  {name: 'environmental protection'},
  {name: 'swimming'},
  {name: 'geodesy'},
  {name: 'theory of probability'},
  {name: 'play on the instruments'},
  {name: 'management'},
  {name: 'physiology'},
  {name: 'Polish language'},
  {name: 'economy'},
  {name: 'voice emission'},
  {name: 'photography'},
  {name: 'higher mathematics'},
  {name: 'cosmetology'},
  {name: 'librarianship'},
  {name: 'programming'},
  {name: 'yoga'},
]
